services:
  postgres:
    image: postgres:16-alpine
    container_name: flowpay-postgres
    environment:
      POSTGRES_DB: flowpay
      POSTGRES_USER: flowpay
      POSTGRES_PASSWORD: flowpay
    ports:
      - "5433:5432"
    volumes:
      - flowpay_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U flowpay -d flowpay" ]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowpay-app
    environment:
      SPRING_PROFILES_ACTIVE: jpa
      DB_URL: jdbc:postgresql://postgres:5432/flowpay
      DB_USERNAME: flowpay
      DB_PASSWORD: flowpay
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  flowpay_postgres_data: